-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE orders (

    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    order_status VARCHAR(50) NOT NULL
);